# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zhanpeng Wang
email: zwang10@haverford.edu
description: > # this means to ignore newlines until "baseurl:"
  Zhanpeng Wang's personal website. Haverford College Class of 2020. Major in Computer Science, and minor in Economics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhanpengwang888.com" # the base hostname & protocol for your site
twitter_username: zhanpeng.wang.7
github_username:  zhanpengwang888

# Build settings
markdown: kramdown
