# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Who is Zhanpeng Wang? # ex. I m Chuan
name: Zhanpeng Wang # ex. DONGChuan
email: zhanpengwang888@gmail.com
location: Boston, MA # ex. Nice, France
company: Haverford College
company_url: https://www.haverford.edu/
github_url: https://github.com/zhanpengwang888 # ex. https://github.com/zhanpengwang888
github_username: zhanpengwang888 # ex. DONGChuan
description: Zhanpeng Wang's personal website. Haverford College Class of 2020. Major in Computer Science, and minor in Economics.
favicon: favicon.png # Image must be in assets/images
repository: zhanpengwang888/zhanpengwang888.github.io # ex. DONGChuan/DONGChuan.github.io
facebook_username: Zhanpeng Wang
facebook_url: https://www.facebook.com/zhanpeng.wang.7
linkedin_username: Zhanpeng Wang
linkedin_url: https://www.linkedin.com/in/zhanpeng-wang-05102a122/

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://zhanpengwang888.github.io/

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: zhanpengwang888githubio.disqus.com # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /projects
    label: Projects

  -
    href: /blog
    label: Blog

  -
    href: /useful_links
    label: Useful Links

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-123175385-1'  # ex. UA-72165600-X

google_analytics: UA-123175385-1

# For about.html. Feel free to create your own!
skill_software_keywords: [Java, C/C++, Python, MySQL, SQLite, Racket, Scheme, Stata 14, Processing]
skill_web_keywords: [HTML5, CSS, JavaScript, JQuery, NodeJS, Flask, Django]
skill_languages: [Mandarin, Cantonese, English, Japanese, Hakka, French, Latin]
courses_taken_so_far: [CMSC395 Mobile Development, CMSC340 Analysis of Algorithms, CMSC240 Computer Organization ,CMSC355 Operating System,
                      CMSC311 Computer Security, CMSC245 Principle to Programming Languages, ECON304 Intro to Econometrics,
                      MATH215 Linear Algebra, CMSC231 Discrete Mathematics, ECON204 Economic Statistics with Calculus, 
                      CMSC105 Intro to CS, CMSC106 Intro to Data Structure, ECON105 Intro to Economics, LING101 Intro to Linguistics,
                      JNSE001-002 First Year Japanese Intensive]