# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Who is Zhanpeng Wang? # ex. Who is Zhanpeng Wang?
name: Zhanpeng Wang # ex. Zhanpeng Wang
email: zhanpengwang888@gmail.com
location: Boston, MA # ex. Boston, MA
company: University of Pennsylvania, School of Engineering and Applied Science
company_url: https://www.seas.upenn.edu/
github_url: https://github.com/zhanpengwang888
github_username: zhanpengwang888 # ex. zhanpengwang888
description: Zhanpeng Wang's personal website. UPenn SEAS Class of 2020. Candidate for Master of Science in Engineering for Computer and Information Science.
favicon: favicon.png # Image must be in assets/images
repository: zhanpengwang888/zhanpengwang888.github.io
facebook_username: Zhanpeng Wang
facebook_url: https://www.facebook.com/zhanpeng.wang.7
linkedin_username: Zhanpeng Wang
linkedin_url: https://www.linkedin.com/in/zhanpeng-wang-05102a122/

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url.
url: https://zhanpengwang888.github.io/
# url: http://localhost:4000

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  syntax_highlighter: coderay

# Disque
disque: zhanpengwang888githubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /projects
    label: Projects

  -
    href: /blog
    label: Blog

  -
    href: /useful_links
    label: Useful Links

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-123175385-1'

google_analytics: UA-123175385-1

# For about.html.
skill_software_keywords: [Python, Java, Kotlin, PHP/Hack, C/C++, MySQL, SQLite, Racket/Scheme, Stata 14, Processing]
skill_web_keywords: [HTML5, CSS, JavaScript, JQuery, NodeJS, Flask, Django]
skill_languages: [English, Hakka, Mandarin, Cantonese, Japanese, French, Latin]
courses_taken_so_far: [CIS555 Internet and Web Systems, CIS521 Artificial Intelligence, CIS519 Applied Machine Learning, CMSC350 Compiler Design,
                      CMSC345 Theory of Computation, CMSC399 Senior Thesis, CMSC356 Concurrency and Co-Design in Operating Systems, ECON200 Intermediate Microeconomics,
                      ECON201 Analytical Economics, CMSC210 Linear Optimization, ECON247 Financial Accounting, 
                      CMSC395 Mobile Development, CMSC340 Analysis of Algorithms, CMSC240 Computer Organization, CMSC355 Operating System,
                      CMSC311 Computer Security, CMSC245 Principle to Programming Languages, ECON304 Intro to Econometrics,
                      MATH215 Linear Algebra, CMSC231 Discrete Mathematics, ECON204 Economic Statistics with Calculus]